// Code generated by goctl. DO NOT EDIT.
// Source: like.proto

package server

import (
	"context"

	"BuzzBox/service/like/rpc/internal/logic"
	"BuzzBox/service/like/rpc/internal/svc"
	"BuzzBox/service/like/rpc/pb"
)

type LikeServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedLikeServer
}

func NewLikeServer(svcCtx *svc.ServiceContext) *LikeServer {
	return &LikeServer{
		svcCtx: svcCtx,
	}
}

func (s *LikeServer) ThumbsUp(ctx context.Context, in *pb.ThumbsUpRequest) (*pb.ThumbsUpResponse, error) {
	l := logic.NewThumbsUpLogic(ctx, s.svcCtx)
	return l.ThumbsUp(in)
}

func (s *LikeServer) IsThumbsUp(ctx context.Context, in *pb.IsThumbsUpRequest) (*pb.IsThumbsUpResponse, error) {
	l := logic.NewIsThumbsUpLogic(ctx, s.svcCtx)
	return l.IsThumbsUp(in)
}
