// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "默认主键"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "逻辑删除时间"},
		{Name: "_delete_", Type: field.TypeUint, Comment: "逻辑标识。0 未删除, 1 已删除", Default: 0},
		{Name: "username", Type: field.TypeString, Comment: "用户名"},
		{Name: "mobile", Type: field.TypeString, Comment: "手机号"},
		{Name: "avatar", Type: field.TypeString, Comment: "头像url"},
		{Name: "password", Type: field.TypeString, Comment: "密码"},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_mobile",
				Unique:  true,
				Columns: []*schema.Column{UserColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UserTable,
	}
)

func init() {
	UserTable.Annotation = &entsql.Annotation{
		Table: "user",
	}
}
