// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: like.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Like_ThumbsUp_FullMethodName   = "/service.Like/ThumbsUp"
	Like_IsThumbsUp_FullMethodName = "/service.Like/IsThumbsUp"
)

// LikeClient is the client API for Like service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LikeClient interface {
	ThumbsUp(ctx context.Context, in *ThumbsUpRequest, opts ...grpc.CallOption) (*ThumbsUpResponse, error)
	IsThumbsUp(ctx context.Context, in *IsThumbsUpRequest, opts ...grpc.CallOption) (*IsThumbsUpResponse, error)
}

type likeClient struct {
	cc grpc.ClientConnInterface
}

func NewLikeClient(cc grpc.ClientConnInterface) LikeClient {
	return &likeClient{cc}
}

func (c *likeClient) ThumbsUp(ctx context.Context, in *ThumbsUpRequest, opts ...grpc.CallOption) (*ThumbsUpResponse, error) {
	out := new(ThumbsUpResponse)
	err := c.cc.Invoke(ctx, Like_ThumbsUp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeClient) IsThumbsUp(ctx context.Context, in *IsThumbsUpRequest, opts ...grpc.CallOption) (*IsThumbsUpResponse, error) {
	out := new(IsThumbsUpResponse)
	err := c.cc.Invoke(ctx, Like_IsThumbsUp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LikeServer is the server API for Like service.
// All implementations must embed UnimplementedLikeServer
// for forward compatibility
type LikeServer interface {
	ThumbsUp(context.Context, *ThumbsUpRequest) (*ThumbsUpResponse, error)
	IsThumbsUp(context.Context, *IsThumbsUpRequest) (*IsThumbsUpResponse, error)
	mustEmbedUnimplementedLikeServer()
}

// UnimplementedLikeServer must be embedded to have forward compatible implementations.
type UnimplementedLikeServer struct {
}

func (UnimplementedLikeServer) ThumbsUp(context.Context, *ThumbsUpRequest) (*ThumbsUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ThumbsUp not implemented")
}
func (UnimplementedLikeServer) IsThumbsUp(context.Context, *IsThumbsUpRequest) (*IsThumbsUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsThumbsUp not implemented")
}
func (UnimplementedLikeServer) mustEmbedUnimplementedLikeServer() {}

// UnsafeLikeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LikeServer will
// result in compilation errors.
type UnsafeLikeServer interface {
	mustEmbedUnimplementedLikeServer()
}

func RegisterLikeServer(s grpc.ServiceRegistrar, srv LikeServer) {
	s.RegisterService(&Like_ServiceDesc, srv)
}

func _Like_ThumbsUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThumbsUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServer).ThumbsUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Like_ThumbsUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServer).ThumbsUp(ctx, req.(*ThumbsUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Like_IsThumbsUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsThumbsUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServer).IsThumbsUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Like_IsThumbsUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServer).IsThumbsUp(ctx, req.(*IsThumbsUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Like_ServiceDesc is the grpc.ServiceDesc for Like service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Like_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Like",
	HandlerType: (*LikeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ThumbsUp",
			Handler:    _Like_ThumbsUp_Handler,
		},
		{
			MethodName: "IsThumbsUp",
			Handler:    _Like_IsThumbsUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "like.proto",
}
